---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.user }}-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ .Values.user }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
